namespace Assets.Core.Enums
{
    public enum CreatureType
    {
        ARMOURED_SKELETON,
        BEAR,
        BOAR,
        FROST_GIANT,
        GHOUL,
        GIANT_RAT,
        GIANT_WORM,
        ICE_SPIDER,
        ICE_TOAD,
        IMP,
        LARGE_CONSTRUCT,
        MAJOR_DEMON,
        MEDIUM_CONSTRUCT,
        MINOR_DEMON,
        SKELETON,
        SMALL_CONSTRUCT,
        SNOW_LEOPARD,
        SNOW_TROLL,
        VAMPIRE,
        WEREWOLF,
        WHITE_GORILLA,
        WILD_DOG,
        WOLF,
        WRAITH,
        ZOMBIE
    }
}